---
# Users configuration for Vostok Linux

# Default settings
defaultGroups:
  - users
  - wheel
  - audio
  - video
  - storage
  - optical
  - network
  - lp
  - scanner
  - power

autologinGroup:  autologin

sudoersGroup:    wheel
sudoersFile:     /etc/sudoers.d/10-installer

setRootPassword: true
doReusePassword: false

allowWeakPasswords: false
allowWeakPasswordsDefault: false

# User shell
userShell: /bin/bash

# Avatar image path (optional)
avatarFilePath: ~/.face
