cursor #dde3ee
cursor_text_color #bbc7db

foreground            #dde3ee
background            #0e141c
selection_foreground  #00363a
selection_background  #80d4dc
url_color             #4dd9e4

color0   #0e141c
color1   #ff4586
color2   #4ce45a
color3   #fff145
color4   #2cccd8
color5   #006169
color6   #4dd9e4
color7   #dcedef
color8   #859394
color9   #ff80ac
color10  #88ff93
color11  #fff688
color12  #6df0fa
color13  #88f6ff
color14  #b3f9ff
color15  #f6feff
