#!/bin/sh
case "${ACTION}" in
post)
	if [ -e usr/lib32 ]; then
		ldconfig usr/lib32
	fi
	if [ -f usr/lib32/libssl.so.3 ] && [ ! -f usr/lib32/libssl.so.1.1 ]; then
		ln -sf libssl.so.3 usr/lib32/libssl.so.1.1
	fi
	if [ -f usr/lib32/libcrypto.so.3 ] && [ ! -f usr/lib32/libcrypto.so.1.1 ]; then
		ln -sf libcrypto.so.3 usr/lib32/libcrypto.so.1.1
	fi
	;;
esac
